services:
  postgres:
    container_name: restaurant_postgres
    image: postgres:16.8
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: restaurant_db
    volumes:
      - restaurant_data:/var/lib/postgresql/data
    ports:
     - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d restaurant_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: restaurant_backend
    build:
      context: ./source/
    environment:
      DATABASE_URL: postgresql+psycopg2://admin:admin@postgres:5432/restaurant_db
    depends_on:
      - postgres
    ports:
      - "5555:5555"

volumes:
 restaurant_data: